### ISSUE TITLE
tech debt: stdlib function imports shadowed by same-named method parameters

### ISSUE THREAD

**Issue by JRedrupp** [JRedrupp/bison#367]
**File**: `bison/_frame.mojo` (import line, `SeriesGroupBy.__init__`)
**Classification**: Code Simplifications — Rename Variable

## Problem

When a stdlib function is imported under the same name as a method parameter, the parameter silently shadows the function in that scope. The compiler catches the misuse at the call site (`'Bool' does not implement the '__call__' method`) but only after the code is written — there is no warning at the shadowing point.

Concrete instance introduced in #359: `from std.builtin.sort import sort` is shadowed by `sort: Bool` in `SeriesGroupBy.__init__`, requiring the import to be aliased as `_sort_list` to avoid the conflict:

```mojo
# Required workaround:
from std.builtin.sort import sort as _sort_list
```

Without the alias the call `sort(self._group_keys)` resolves to the `Bool` parameter, not the sort function.

## Risk

Any future method that takes a parameter named `min`, `max`, `sum`, `len`, `print`, `sort`, etc. will silently shadow the corresponding stdlib import. The bug only surfaces when the imported name is called, not when the parameter is declared.

## Fix

Adopt a project-wide convention for imported utility functions that are likely to conflict with parameter names: always import them with a leading underscore (e.g. `sort as _sort_list`, `len as _len`) or use the fully-qualified module path at the call site. Document the convention in `CLAUDE.md` or a code-style note.
