### ISSUE TITLE
fix: test_functional.mojo and test_series_transforms.mojo fail to link under mojo build

### ISSUE THREAD

**Issue by JRedrupp** [JRedrupp/bison#661]
## Problem

Two test files fail to link when compiled with `mojo build` due to a missing `libm` dependency:

```
/usr/bin/ld: /tmp/mojo_archive-*.a: undefined reference to symbol 'log10@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
mojo: error: failed to link executable
```

Affected files:
- `tests/test_functional.mojo`
- `tests/test_series_transforms.mojo`

Both files work fine with `mojo run` (which links differently). The issue is that `mojo build` doesn't automatically link `-lm` when math functions (`log10`, `sqrt`, etc.) are used.

## Impact

Low — these tests pass via `mojo run` in CI. The `check_compile.sh` script classifies these as "link-only warnings" rather than errors.

## Possible fixes

1. Report upstream to Modular — `mojo build` should auto-link libm when math stdlib functions are used
2. Workaround: pass linker flags if `mojo build` supports them

## Found by

`pixi run check-compile` (introduced in #659)
